### ISSUE TITLE
无法键入代码

### ISSUE THREAD

**Issue by Tosd0** [FoskyM/flarum-nickname-group-formatter#1]
如图，无法键入任何代码，只能选中这个输入框但无法输入/复制
flarum版本 1.8.2

<img width="340" alt="image" src="https://github.com/FoskyM/flarum-nickname-group-formatter/assets/65720409/ee416ef2-76bc-4212-b0bc-a0111e3d9390">

**Comment by FoskyM** [comment]
这个问题我在刚上传完代码后发现了，一直没修（毕竟没想过还有人会用）
等过段时间空了再修

**Comment by Tosd0** [comment]
> 这个问题我在刚上传完代码后发现了，一直没修（毕竟没想过还有人会用）
> 等过段时间空了再修

草草 好
感觉这个功能好玩

**Comment by FoskyM** [comment]
v1.0.3 版本已修复，感谢支持
